/**
 * Handing generated bytes to the browser as a file download.
 *
 * The only DOM-dependent part of the export path; everything upstream of it is
 * pure so it can be tested in node.
 */

/**
 * Save `bytes` to the user's downloads as `filename`.
 *
 * The array is typed over `ArrayBuffer` (not the wider `ArrayBufferLike`)
 * because `Blob` will not take a view onto a `SharedArrayBuffer`.
 */
export function downloadBytes(
    bytes: Uint8Array<ArrayBuffer>,
    filename: string,
    mimeType: string,
): void {
    const url = URL.createObjectURL(new Blob([bytes], { type: mimeType }));
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
}
